/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppMenu: typeof import('./components/app/AppMenu.vue')['default']
    AppMenuItem: typeof import('./components/app/AppMenuItem.vue')['default']
    AppSidebar: typeof import('./components/app/AppSidebar.vue')['default']
    AppTopbar: typeof import('./components/app/AppTopbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
